version: "3.7"
services:
  grafana:
    image: grafana/grafana:7.0.3
    container_name: grafana
    restart: always
    ports:
      - 4000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
  client_cron_metrics:
    restart: always
    build:
      context: .
      dockerfile: ./config/client/Dockerfile
    container_name: client_cron_metrics
    entrypoint:
        - /entrypoint.sh
    working_dir: /client_cron_metrics/
    volumes:
      - ./client_cron_metrics:/client_cron_metrics

networks:
  monitoring:
    driver: bridge
    ipam:
     config:
       - subnet: 178.17.22.0/24

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true