version: "3.7"
services:
  grafana:
    image: grafana/grafana:7.1.3
    container_name: grafana
    restart: on-failure
    ports:
      - 4000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: on-failure
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin1234
      - INFLUXDB_USER=admin2
      - INFLUXDB_PASSWORD=admin1234
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_HTTP_READINESS_TIMEOUT=30
  client_cron_metrics:
    restart: always
    hostname: docker-client
    build:
      context: .
      dockerfile: ./config/client/Dockerfile
    container_name: client_cron_metrics
    entrypoint:
        - /entrypoint.sh
    working_dir: /client_cron_metrics/
    volumes:
      - ./client_cron_metrics:/client_cron_metrics
    depends_on:
      - server_metrics
  server_metrics:
    restart: always
    build:
      context: .
      dockerfile: ./config/server/Dockerfile
    container_name: server_metrics
    entrypoint:
        - /entrypoint.sh
    working_dir: /server_metrics/
    ports:
      - 5005:5005
    networks:
      - monitoring
    volumes:
      - ./server_metrics:/server_metrics
    depends_on:
      - influxdb
networks:
  monitoring:
    driver: bridge
    ipam:
     config:
       - subnet: 178.17.22.0/24

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true